afrodisiaca(excita_apetito_sexual).
analgesica(quita_dolor).
anestesica(insensibiliza_partes_del_cuerpo).
antidiarreica(controla_diarreas).
antiespamodica(controla_espasmos).
antiflogistica(contra_inflamaciones).
antipiretica(quita_fiebre).
antiseptica(mata_tejidos).
aperitiva(produce_apetito).
astringente(contraer_tejidos).
carminativa(evita_gases).
colagoga(expulsa_bilis).
depurativa(limpia_sangre).
diaforetica(provoca_sudar).
digestiva(favorece_digestion).
diuretica(provoca_orina).
emetica(provoca_nauseas_vomitos).
emenagoga(activa_menstruacion).
estupefaciente(aquieta_duerme_atonta).
expectorante(expulsa_flemas_mucosidades).
hemostatica(detiene_hemorragias).
hepatica(ayuda_higado).
laxante(purga_sin_diarrea).
pectoral(ayuda_pecho).
sedante(calma_dolores_intestinales).
tonica(da_fuerza_organismo).
toxica(venenosa).
vermifuga(expulsa_gusanos_intestinales).
vulneraria(cura_llagas_heridas).

forma_uso(cocimiento).
forma_uso(infusion).
forma_uso(maceracion).
forma_uso(jarabe).
forma_uso(tintura).
forma_uso(jugo).
forma_uso(horchata).

trata(malva, abcesos).
trata(zarzaparrilla, abceso_hepatico).
trata(anis, acidez_estomacal).
trata(perejil, acidez_estomacal).
trata(sanguinaria, acido_urico).
trata(limon, acido_urico).
trata(sauco, acido_urico).
trata(arnica, acne).
trata(llanten, aftas).
trata(fenogreco, aftas).
trata(zarzamora, aftas).
trata(salvia, agotamiento).
trata(tilo, agotamiento).
trata(valeriana, agotamiento).
trata(yerbabuena, agruras).
trata(manzanilla, agruras).
trata(jugo_limon_toronja, agruras).
trata(pinguica, albuminaria).
trata(quina_roja, albuminaria).
trata(encino_rojo, albuminaria).
trata(pimiento, alcoholismo).
trata(salvia, almorranas).
trata(hamamelis, almorranas).
trata(sanguinaria, almorranas).
trata(cola_de_caballo, almorranas).
trata(arnica, almorranas).
trata(sauco, almorranas).
trata(ajenjo, anemia).
trata(germen_de_trijo, anemia).
trata(quina, anemia).
trata(canela, anemia).
trata(alholva, anemia).
trata(eucalito, anginas).
trata(cebada, anginas).
trata(salvia, anginas).
trata(tabachin, anginas).
trata(borraja, anginas).
trata(ajenjo, anorexia).
trata(genciana, anorexia).
trata(yerbabuena, anorexia).
trata(limon, arterosclerosis).
trata(genciana, arterosclerosis).
trata(cardo, arterosclerosis).
trata(zarzaparrilla, arterosclerosis).
trata(arnica, arterosclerosis).
trata(chicalote, arterosclerosis).
trata(alcanfor, arterosclerosis).
trata(toronja, arterosclerosis).
trata(limon, artritis).
trata(genciana, artritis).
trata(cardo, artritis).
trata(zarzaparrilla, artritis).
trata(arnica, artritis).
trata(chicalote, artritis).
trata(alcanfor, artritis).
trata(toronja, artritis).
trata(eucalito, asma).
trata(merrubio, asma).
trata(toloache, asma).
trata(dregano, asma).
trata(salvia, asma).
trata(lupulo, atonia_estomacal).
trata(eucalito, atonia_estomacal).
trata(cuasia, atonia_estomacal).
trata(uva, bazo).
trata(cerezo, bazo).
trata(malva, boca_inflamacion).
trata(rosal, boca_inflamacion).
trata(limon, boca_inflamacion).
trata(salvia, boca_inflamacion).
trata(rosal, boca_estomatitis).
trata(encina, boca_estomatitis).
trata(salvia, boca_estomatitis).
trata(zarzamora, boca_estomatitis).
trata(eucalito, bronquitis).
trata(borraja, bronquitis).
trata(anacahuite, bronquitis).
trata(gordolobo, bronquitis).
trata(tilo, bronquitis).
trata(benjui, bronquitis).
trata(marrubio, bronquitis).
trata(rabano, bronquitis).
trata(gordolobo, bronconeumonia).
trata(eucalito, bronconeumonia).
trata(ipecacuana, bronconeumonia).
trata(mostaza, bronconeumonia).
trata(ortiga, cabello).
trata(espinosilla, cabello).
trata(marrubio, cabello).
trata(romero, cabello).
trata(anis, calambres).
trata(tila, calambres).
trata(manzanilla, calambres).
trata(ajenjo, calambres).
trata(diente_de_leon, calculos_biliares).
trata(aceite_de_oliva, calculos_biliares).
trata(retama, calculos_biliares).
trata(cabellos_de_elote, calculos_renales).
trata(pinguica, calculos_renales).
trata(cola_de_caballo, calculos_renales).
trata(ajo, callos).
trata(cebolla, callos).
trata(hiedra, caries).
trata(cola_de_caballo, caries).
trata(ortiga, caspa).
trata(limon, caspa).
trata(romero, caspa).
trata(cuachalalate, cancer_del_utero).
trata(llanten, cancer_del_utero).
trata(siempreviva, cancer_del_utero).
trata(mastuerzo, ciatica).
trata(higuera, ciatica).
trata(sauco, ciatica).
trata(toronjil, circulacion).
trata(sanguinaria, circulacion).
trata(salvia, circulacion).
trata(hamamelis, circulacion).
trata(cola_de_caballo, cistitis).
trata(doradilla, cistitis).
trata(ajo, cistitis).
trata(cabellos_de_elote, cistitis).
trata(menta, colicos).
trata(honojo, colicos).
trata(manzanilla, colicos).
trata(toronjil, colicos).
trata(boldo, colicos).
trata(linaza, colitis).
trata(anis, colitis).
trata(romero, colitis).
trata(cola_de_caballo, colitis).
trata(arnica, contusiones).
trata(hamamelis, contusiones).
trata(laurel, contusiones).
trata(brionia, contusiones).
trata(digital, corazon).
trata(salvia, corazon).
trata(nuez_de_kola, corazon).
trata(tejocote, corazon).
trata(achicoria, depurativos_de_la_sangre).
trata(diente_de_leon, depurativos_de_la_sangre).
trata(apio, depurativos_de_la_sangre).
trata(sanguinaria, depurativos_de_la_sangre).
trata(zarzaparrilla, depurativos_de_la_sangre).
trata(berro, depurativos_de_la_sangre).
trata(matarique, diabetes).
trata(tronadora, diabetes).
trata(eucalito, diabetes).
trata(damiana, diabetes).
trata(capulin, diarrea_cronica).
trata(mezquite, diarrea_cronica).
trata(tlalchichinole, diarrea_cronica).
trata(linaza, diarrea_irritacion).
trata(membrillo, diarrea_irritacion).
trata(arroz, diarrea_irritacion).
trata(cebada, diarrea_irritacion).
trata(guayaba, diarrea_inflamacion).
trata(albahaca, diarrea_inflamacion).
trata(granada, diarrea_inflamacion).
trata(manzanilla, diarrea_verdosa).
trata(simonillo, diarrea_verdosa).
trata(siempreviva, diarrea_verdosa).
trata(chaparro_amargoso, diarrea_con_sangre).
trata(muicle, diarrea_con_sangre).
trata(monacillo, diarrea_con_sangre).
trata(limon, difteria).
trata(naranja, difteria).
trata(tamarindo, disenteria).
trata(chaparro_amargoso, disenteria).
trata(ipecacuana, disenteria).
trata(cedron, disenteria).
trata(anis, dispepsia_hiperc).
trata(menta, dispepsia_hiperc).
trata(yerbabuena, dispepsia_hiperc).
trata(diente, dispepsia_hiperc).
trata(te_limon, dispepsia_hiperc).
trata(quina, dispepsia_hipoc).
trata(genciana, dispepsia_hipoc).
trata(tabaquillo, dispepsia_hipoc).
trata(anis_estrella, dolor).
trata(valeriana, dolor).
trata(manzanilla, dolor).
trata(alcanfor, dolores_musculares).
trata(tamarindo, empacho).
trata(linaza, enteritis).
trata(cedron, enteritis).
trata(llanten, enteritis).
trata(valeriana, epilepsia).
trata(hierba_de_pollo, epistaxis).
trata(cebolla, epistaxis).
trata(perejil, epistaxis).
trata(sauco, erisipela).
trata(hiedra, erisipela).
trata(zanahoria, erisipela).
trata(borraja, escarlatina).
trata(sauco, escarlatina).
trata(cebolla, escarlatina).
trata(ajo, escorbuto).
trata(limon, escorbuto).
trata(berro, escorbuto).
trata(cebolla, escorbuto).
trata(geranio, escorbuto).
trata(ciruela, estreñimiento).
trata(linaza, estreñimiento).
trata(cjia, estreñimiento).
trata(tamarindo, estreñimiento).
trata(agar-agar, estreñimiento).
trata(eucalito, faringitis).
trata(lavanda, faringitis).
trata(anacahuite, faringitis).
trata(apio, flatulencias).
trata(tornillo, flatulencias).
trata(perejil, flatulencias).
trata(anis_estrella, flatulencias).
trata(hinojo, flatulencias).
trata(toronjil, flatulencias).
trata(romero, flatulencias).
trata(ruibarbo, flatulencias).
trata(ruda, flatulencias).
trata(menta, flatulencias).
trata(arnica, flebitis).
trata(alfalfa, flebitis).
trata(lino, flebitis).
trata(malvadisco, flebitis).
trata(romero, flebitis).
trata(quina, flebitis).
trata(genciana, flemas).
trata(oregano, flemas).
trata(fenogreco, forunculos).
trata(malvavisco, forunculos).
trata(hiedra, forunculos).
trata(manzanilla, gastralgia).
trata(anis_estrella, gastralgia).
trata(cola_de_caballo, gonorrea).
trata(doradilla, gonorrea).
trata(zarzaparrilla, gonorrea).
trata(apio, gota).
trata(cerezo, gota).
trata(limon, gota).
trata(pino, gota).
trata(alcanfor, gota).
trata(aconito, gota).
trata(belladona, gota).
trata(beleño, gota).
trata(colchico, gota).
trata(chicalote, gota).
trata(encina, grietas_del_ano).
trata(encina, grietas_de_pezon).
trata(nogal, grietas_de_pezon).
trata(milenrama, grietas_de_pezon).
trata(eucalito, gripe).
trata(limon, gripe).
trata(quina, gripe).
trata(zarzaparrilla, gripe).
trata(calendula, gripe).
trata(hinojo, halitosis).
trata(menta, halitosis).
trata(mastuerzo, hemorragia_interna).
trata(ortigal, hemorragia_interna).
trata(rosal, hemorragia_interna).
trata(retama, hepatitis).
trata(boldo, hepatitis).
trata(alcachofa, hepatitis).
trata(prodigiosa, hepatitis).
trata(cascara_sagrada, hepatitis).
trata(helecho, hernia).
trata(ricino, hernia).
trata(tabaco, hernia).
trata(linaza, herpes).
trata(llanten, herpes).
trata(arnica, heridas).
trata(hamamelis, heridas).
trata(alcachofa, hidropesia).
trata(cardo, hidropesia).
trata(perejil, hidropesia).
trata(sauco, hidropesia).
trata(berros, hidropesia).
trata(retama, hidropesia).
trata(marrubio, higado_congestion).
trata(boldo, higado_congestion).
trata(doradilla, higado_congestion).
trata(ruibarbo, higado_congestion).
trata(manzanilla, higado_colicos).
trata(lechuga, higado_bilis).
trata(tila, higado_bilis).
trata(papaloquelite, higado_ictericia).
trata(achicoria, higado_ictericia).
trata(berros, higado_ictericia).
trata(llanten, higado_ictericia).
trata(retama, higado_ictericia).
trata(tecomazuchil, higado_ictericia).
trata(ajo, hipertension).
trata(esparrago, hipertension).
trata(alpiste, hipertension).
trata(muerdago, hipertension).
trata(miel, hipotension).
trata(nuez_de_kola, hipotension).
trata(crategus, hipotension).
trata(acedera, hipotension).
trata(anis, hipo).
trata(hinojo, hipo).
trata(tila, hipo).
trata(valeriana, hipo).
trata(azahar, histerismo).
trata(beleño, histerismo).
trata(gelsemio, histerismo).
trata(tila, histerismo).
trata(valeriana, histerismo).
trata(pasiflora, insomnio).
trata(azahar, insomnio).
trata(menta, insomnio).
trata(manzanilla, insomnio).
trata(lechuga, insomnio).
trata(tila, insomnio).
trata(genciana, intestino).
trata(melisa, intestino).
trata(yohimbo, impotencia_sexual).
trata(damiana, impotencia_sexual).
trata(nuez_vomica, impotencia_sexual).
trata(aguacate, impotencia_sexual).
trata(manzanilla, jaqueca).
trata(aconito, jaqueca).
trata(valeriana, jaqueca).
trata(tila, jaqueca).
trata(chicalote, jaqueca).
trata(hinojo, lactancia).
trata(anis, lactancia).
trata(menta, lactancia).
trata(perejil, lactancia).
trata(zanahoria, lactancia).
trata(aconito, laringitis).
trata(borraja, laringitis).
trata(cebolla, laringitis).
trata(rosa, laringitis).
trata(benjui, laringitis).
trata(encino, laringitis).
trata(encina, leucorrea).
trata(zarzaparrilla, leucorrea).
trata(pino, leucorrea).
trata(enebro, leucorrea).
trata(genciana, leucorrea).
trata(ajenjo, lombrices).
trata(ajo, lombrices).
trata(cebolla, lombrices).
trata(brionia, lombrices).
trata(aguacate, lombrices).
trata(papaya, lombrices).
trata(epazote, lombrices).
trata(avena, lumbago).
trata(cebada, lumbago).
trata(tornillo, lumbago).
trata(verbena, lumbago).
trata(fenogreco, llagas).
trata(eucalito, llagas).
trata(llanten, llagas).
trata(sanguinaria, llagas).
trata(quina, malaria).
trata(girasol, malaria).
trata(eucalito, malaria).
trata(cardo, malaria).
trata(azahar, menopausia).
trata(hamamelis, menopausia).
trata(tila, menopausia).
trata(quina_roja, menopausia).
trata(azafran, menstruacion_abundante).
trata(hamamelis, menstruacion_abundante).
trata(belladona, menstruacion_dolorosa).
trata(anis_estrella, menstruacion_dolorosa).
trata(ruda, menstruacion_escasa).
trata(ajenjo, menstruacion_escasa).
trata(manzanilla, menstruacion_escasa).
trata(apio, menstruacion_irregular).
trata(hisopo, menstruacion_irregular).
trata(quina_amarilla, menstruacion_irregular).
trata(sabina, menstruacion_irregular).
trata(artemisa, menstruacion_irregular).
trata(hamamelis, metorragia).
trata(zoapatle, metorragia).
trata(perejil, metorragia).
trata(cuerrecillo_centeno, metorragia).
trata(clavo, muelas).
trata(hiedra, muelas).
trata(ortiga, nariz).
trata(cola_de_caballo, nariz).
trata(ruda, nariz).
trata(eucalito, nariz).
trata(anis, nauseas).
trata(ajenjo, nauseas).
trata(menta, nauseas).
trata(salvia, nauseas).
trata(manzanilla, neuralgias).
trata(menta, neuralgias).
trata(valeriana, neuralgias).
trata(boldo, neuralgias).
trata(pasiflora, neurastenia).
trata(te_negro, neurastenia).
trata(mate, neurastenia).
trata(valeriana, neurastenia).
trata(linaza, nefritis).
trata(grama, nefritis).
trata(cebada, nefritis).
trata(llanten, nefritis).
trata(doradilla, nefritis).
trata(esparrago, nefritis).
trata(ruda, nefritis).
trata(toronjil, obesidad).
trata(marrubio, obesidad).
trata(limon, obesidad).
trata(malva, obesidad).
trata(esparrago, obesidad).
trata(boldo, oidos).
trata(aceite_de_oliva, oidos).
trata(llanten, oidos).
trata(hiedra, oidos).
trata(manzanilla, ojos).
trata(limon, ojos).
trata(llanten, ojos).
trata(salvia, ojos).
trata(ruda, ojos).
trata(rosal, ojos).
trata(ajenjo, paludismo).
trata(quina, paludismo).
trata(berro, pecas).
trata(genciana, pecas).
trata(rabano, pecas).
trata(papaya, pecas).
trata(laurel, pies_olorosos).
trata(encina, pies_olorosos).
trata(miel, piquetes_abeja).
trata(perejil, piquetes_abeja).
trata(cebolla, piquetes_abeja).
trata(puerro, piquetes_abeja).
trata(fresno, piquetes_araña).
trata(ipecacuana, piquetes_araña).
trata(alcanfor, piquetes_mosco).
trata(perejil, piquetes_mosco).
trata(hamamelis, piquetes_mosco).
trata(anagalida, piquetes_vibora).
trata(jengible, pleuresia).
trata(linaza, pleuresia).
trata(cardo, pleuresia).
trata(girasol, pleuresia).
trata(ipecacuana, piorrea).
trata(cola_de_caballo, prostata).
trata(eucalito, pulmonia).
trata(ocote, pulmonia).
trata(gordolobo, pulmonia).
trata(borraja, pulmonia).
trata(sauco, pulmonia).
trata(linaza, quemaduras).
trata(cebolla, quemaduras).
trata(hiedra, quemaduras).
trata(gordolobo, quemaduras).
trata(nogal, raquitismo).
trata(ajo, reumatismo).
trata(apio, reumatismo).
trata(borraja, reumatismo).
trata(gobernadora, reumatismo).
trata(pino, reumatismo).
trata(romero, reumatismo).
trata(sanguinaria, reumatismo).
trata(marrubio, reumatismo).
trata(tabaco, reumatismo).
trata(cabello_de_elote, riñones).
trata(cola_de_caballo, riñones).
trata(apio, riñones).
trata(eucalito, ronquera).
trata(pino, ronquera).
trata(gordolobo, ronquera).
trata(ajo, sabañones).
trata(cebolla, sabañones).
trata(estafiate, san_vito).
trata(valeriana, san_vito).
trata(borraja, sarampion).
trata(ortiga, sarampion).
trata(sauco, sarampion).
trata(ajo, sarna).
trata(alcanfor, sarna).
trata(menta, sarna).
trata(tornillo, sarna).
trata(romero, sarna).
trata(encina, sarpullido).
trata(salvia, sarpullido).
trata(tila, sarpullido).
trata(limon, sed).
trata(tamarindo, sed).
trata(pirul, sed).
trata(semilla_de_calabaza, solitaria).
trata(raiz_de_granado_agrio, solitaria).
trata(coquito_de_aceite, solitaria).
trata(helecho_macho, solitaria).
trata(encina, sudoracion_excesiva).
trata(alcanfor, tifoidea).
trata(borraja, tifoidea).
trata(quina, tifoidea).
trata(canela, tifoidea).
trata(romero, tifoidea).
trata(salvia, tifoidea).
trata(berro, tiña).
trata(tila, tiña).
trata(tamarindo, tiña).
trata(salvia, tiña).
trata(eucalito, tos).
trata(capulin, tos).
trata(cedron, tos).
trata(salvia, tos).
trata(malva, tos).
trata(marrubio, tos).
trata(gelsemio, tos_ferina).
trata(quina, tos_ferina).
trata(rabano, tos_ferina).
trata(violeta, tos_ferina).
trata(jugo_de_vastago_de_platano_morado, tuberculosis).
trata(mastuerzo, tuberculosis).
trata(berro, tuberculosis).
trata(ajo, tuberculosis).
trata(eucalito, tuberculosis).
trata(pirul, tuberculosis).
trata(pino, tuberculosis).
trata(roble, tuberculosis).
trata(cuachalalate, ulcera).
trata(sanguinaria, ulcera).
trata(cola_de_caballo, ulcera).
trata(girasol, ulcera).
trata(limon, urticaria).
trata(ruibarbo, urticaria).
trata(hamamelis, varices).
trata(castaño_de_indias, varices).
trata(llanten, varices).
trata(toronjil, varices).
trata(apio, vejija).
trata(cipres, vejija).
trata(cola_de_caballo, vejija).
trata(ortiga, vejija).
trata(malva, vejija).
trata(leche_de_higuera, verrugas).
trata(cebolla, verrugas).
trata(nogal, verrugas).
trata(albahaca, vertigos).
trata(espino, vertigos).
trata(menta, vomitos).
trata(tila, vomitos).
trata(marrubio, vomitos).
trata(valeriana, vomitos).
trata(salvia, vomitos).
trata(cilantro, voz).
trata(ajo, voz).
trata(limon, voz).
trata(pino, voz).
trata(alfalfa, vitaminas).
trata(espinacas, vitaminas).
trata(acelga, vitaminas).
trata(berro, vitaminas).
trata(cebolla, vitaminas).
trata(limon, vitaminas).
trata(zanahoria, vitaminas).
trata(aceite_de_bacalao, vitaminas).




